GET {{host}}/adCampaigns
Accept: json
# {"data": [
#    {
#      "id": 1,
#      "title": "asd",
#      "subtitle": "asd",
#      "text": "asdf",
#      "buttonText": "asf",
#      "buttonUrl": "/",
#      "background": "/static/img/1447ecf79609a769c04abb2f7c8c290a.png",
#      "fontColor": "dark"/"light"
#    }
# ]}

###
GET {{host}}/workshops
Accept: json
# { "data": {
#    "workshops": [
#      {
#        "id": 1,
#        "title": "Воркшоп 1",
#        "description": "Вот такой вот воркшоп",
#        "url": ""
#      }
#    ]
#  }
# }