# Generated by Django 3.1.3 on 2020-11-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workshop', verbose_name='Воркшоп')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('blogCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.blogcategory', verbose_name='Категория блога')),
            ],
        ),
    ]
