# Generated by Django 3.0.8 on 2020-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(max_length=511, verbose_name='Ссылка кнопки')),
            ],
        ),
    ]
