# Generated by Django 3.0.8 on 2020-12-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201206_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdCampaigns',
            new_name='AdCampaign',
        ),
    ]
