# Generated by Django 3.0.8 on 2020-12-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201208_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcampaign',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
