# Generated by Django 3.0.8 on 2020-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201208_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='background',
            field=models.ImageField(default=0, upload_to='', verbose_name='Фон'),
            preserve_default=False,
        ),
    ]
