# Generated by Django 3.1.4 on 2020-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201208_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='font_color',
            field=models.CharField(default='000000', max_length=6, verbose_name='Цвет шрифта'),
        ),
    ]
